name: 'Hello World Template'
description: 'Composite Action Template'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: false
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Set Greeting
      shell: bash
      run: echo "Hello $INPUT_WHO_TO_GREET."
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}

    - name: Random Number Generator
      shell: bash
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT

    - name: Read Output
      shell: bash
      run: |
        echo output: ${{ steps.random-number-generator.outputs.random-number }}
